### ISSUE TITLE
Cryptic error message

### ISSUE THREAD

**Issue by aboritskiy** [r0fls/Fastly-Service-CLI#1]
In case one calls the tool with the wrong API_KEY it brakes with cryptic error message:

```
Traceback (most recent call last):
  File "services.py", line 338, in <module>
    main(args)
  File "services.py", line 314, in main
    new_service = clone_service(args.name, api_key=args.key)
  File "services.py", line 216, in clone_service
    service_id = get_service(name, api_key)["id"]
  File "services.py", line 68, in get_service
    if service["name"] == name], key=lambda x: x["version"])
TypeError: string indices must be integers
```

maybe some simple error handling can be added to show more meaningful error.

**Comment by r0fls** [comment]
Thanks. This is slightly better now:

```
$ python services.py --name someservice --backend test.com --key                        [31/1582]
 blahblah
Traceback (most recent call last):
  File "services.py", line 343, in <module>
    main(args)
  File "services.py", line 316, in main
    new_service = clone_service(args.name, api_key=args.key)
  File "services.py", line 218, in clone_service
    service_id = get_service(name, api_key)["id"]
  File "services.py", line 67, in get_service
    raise UsageException("Received error from Fastly: {}".format(services.text))
__main__.UsageException: Received error from Fastly: {"msg":"Provided credentials are missing or invalid"}
```

**Comment by r0fls** [comment]
fixed by passing the error from here:
https://github.com/r0fls/Fastly-Service-CLI/blob/master/services.py#L66
